// <auto-generated />
using BDD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstBD.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20240226203358_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BDD.Cerveza", b =>
                {
                    b.Property<int>("CervezaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CervezaID"), 1L, 1);

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("CervezaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CervezaID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Cerveza", (string)null);
                });

            modelBuilder.Entity("BDD.Jugo", b =>
                {
                    b.Property<int>("JugoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JugoID"), 1L, 1);

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("JugoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JugoID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Jugo", (string)null);
                });

            modelBuilder.Entity("BDD.Vino", b =>
                {
                    b.Property<int>("VinoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VinoID"), 1L, 1);

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("VinoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VinoID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Vino", (string)null);
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"), 1L, 1);

                    b.Property<bool>("EsAlcoholica")
                        .HasColumnType("bit");

                    b.Property<int>("GradosA")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("BDD.Cerveza", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany("Cervezas")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BDD.Jugo", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany("Jugo")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("BDD.Vino", b =>
                {
                    b.HasOne("Categoria", "Categoria")
                        .WithMany("Vino")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Categoria", b =>
                {
                    b.Navigation("Cervezas");

                    b.Navigation("Jugo");

                    b.Navigation("Vino");
                });
#pragma warning restore 612, 618
        }
    }
}
